name: Publish package

on:
    release:
        types:
            - created
    pull_request:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install dependencies
              run: yarn install --frozen-lockfile
            - name: Run Linter
              run: yarn lint
            - name: Run Unit Tests
              run: yarn test-unit
            - name: Run Integrations Tests
              run: yarn test-int

    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build package
              run: yarn build

    publish-npm:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: yarn publish
              env:
                NODE_AUTH_TOKEN: ${{secrets.npm_token}}

#   publish-gpr:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v1
#         with:
#           node-version: 12
#           registry-url: https://npm.pkg.github.com/
#       - run: npm ci
#       - run: npm publish
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
